spring:
  config:
    activate:
      on-profile: develop

  r2dbc:
    url: r2dbc:h2:mem:///test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
    initialization-mode: always
    port: 9091

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG

msa:
  client-url:
    contents: http://localhost:8082 # 작품 서비스 주소
    history: http://localhost:8083 # 이력 서비스 주소
