# 웹툰 서비스 플랫폼 API Test

### 평가 등록
POST http://localhost:8080/contents/evaluation-register
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJtZW1iZXJUb2tlbiI6IjQ5MmJjMjEzLTVjNDctNDIyZi05MzkwLTFiMGMyMjA2YmNiZSIsImlhdCI6MTY1OTc2NDY4NywiZXhwIjoyNjA1ODQ0Njg3fQ.d82eq4XecwOczhNFmay9bQ6N9IXjXAE_1wlg7Ox_dTc

{
  "memberToken": "108358d3-72cc-47eb-8fb2-d1635c95ab13",
  "contentsToken": "4ff3f414-7a5e-4ce1-8234-76788b5eff13",
  "evaluationType": "LIKE",
  "comment": "댓글"
}

### 좋아요/싫어요 Top3 작품 조회
GET http://localhost:8080/contents/evaluation-top3
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJtZW1iZXJUb2tlbiI6IjQ5MmJjMjEzLTVjNDctNDIyZi05MzkwLTFiMGMyMjA2YmNiZSIsImlhdCI6MTY1OTc2NDY4NywiZXhwIjoyNjA1ODQ0Njg3fQ.d82eq4XecwOczhNFmay9bQ6N9IXjXAE_1wlg7Ox_dTc

### 작품별 조회 이력 페이지
GET http://localhost:8080/history/contents/page?page=1&size=10&contentsToken=4ff3f414-7a5e-4ce1-8234-76788b5eff01
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJtZW1iZXJUb2tlbiI6IjQ5MmJjMjEzLTVjNDctNDIyZi05MzkwLTFiMGMyMjA2YmNiZSIsImlhdCI6MTY1OTc2NDY4NywiZXhwIjoyNjA1ODQ0Njg3fQ.d82eq4XecwOczhNFmay9bQ6N9IXjXAE_1wlg7Ox_dTc

### 사용자 조회 이력 페이지
GET http://localhost:8080/history/search/page?page=1&size=10&weekInterval=1&adultOnly=Y&historyCount=3
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJtZW1iZXJUb2tlbiI6IjQ5MmJjMjEzLTVjNDctNDIyZi05MzkwLTFiMGMyMjA2YmNiZSIsImlhdCI6MTY1OTc2NDY4NywiZXhwIjoyNjA1ODQ0Njg3fQ.d82eq4XecwOczhNFmay9bQ6N9IXjXAE_1wlg7Ox_dTc

### 가격 변경
PUT http://localhost:8080/contents/pricing-modify
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJtZW1iZXJUb2tlbiI6IjQ5MmJjMjEzLTVjNDctNDIyZi05MzkwLTFiMGMyMjA2YmNiZSIsImlhdCI6MTY1OTc2NDY4NywiZXhwIjoyNjA1ODQ0Njg3fQ.d82eq4XecwOczhNFmay9bQ6N9IXjXAE_1wlg7Ox_dTc

{
  "contentsToken": "4ff3f414-7a5e-4ce1-8234-76788b5eff12",
  "pricingType": "PAY",
  "coin": 100
}

### 회원 삭제
DELETE http://localhost:8080/member/delete/108358d3-72cc-47eb-8fb2-d1635c95abf7
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJtZW1iZXJUb2tlbiI6IjQ5MmJjMjEzLTVjNDctNDIyZi05MzkwLTFiMGMyMjA2YmNiZSIsImlhdCI6MTY1OTc2NDY4NywiZXhwIjoyNjA1ODQ0Njg3fQ.d82eq4XecwOczhNFmay9bQ6N9IXjXAE_1wlg7Ox_dTc
